services:
  nginx:
    image: nginx:alpine
    ports:
      - "${PORT_1}:80"
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf:ro
    networks:
      - evd-network
    depends_on:
      - api.evd
      - app.evd

  # redis:
  #   image: redis:7-alpine
  #   ports:
  #     - "6379:6379"
  #   volumes:
  #     - redis_data:/data
  #   networks:
  #     - evd-network

  api.evd:
    image: ghcr.io/sistema-evaluacion-docente/api.evd:latest
    expose:
      - "8000"
    environment:
      - PORT=8000
      - DATABASE_URL=${DATABASE_URL}
      - REDIS_URL=${REDIS_URL}
      - ALLOWED_ORIGINS=${ALLOWED_ORIGINS}
      - FIREBASE_TYPE=${FIREBASE_TYPE}
      - FIREBASE_PROJECT_ID=${FIREBASE_PROJECT_ID}
      - FIREBASE_PRIVATE_KEY_ID=${FIREBASE_PRIVATE_KEY_ID}
      - FIREBASE_PRIVATE_KEY=${FIREBASE_PRIVATE_KEY}
      - FIREBASE_CLIENT_EMAIL=${FIREBASE_CLIENT_EMAIL}
      - FIREBASE_CLIENT_ID=${FIREBASE_CLIENT_ID}
      - FIREBASE_AUTH_URI=${FIREBASE_AUTH_URI}
      - FIREBASE_TOKEN_URI=${FIREBASE_TOKEN_URI}
      - FIREBASE_AUTH_PROVIDER_X509_CERT_URL=${FIREBASE_AUTH_PROVIDER_X509_CERT_URL}
      - FIREBASE_CLIENT_X509_CERT_URL=${FIREBASE_CLIENT_X509_CERT_URL}
      - FIREBASE_UNIVERSE_DOMAIN=${FIREBASE_UNIVERSE_DOMAIN}
      - SEED_ADMIN_INSTITUTIONAL_CODE=${SEED_ADMIN_INSTITUTIONAL_CODE}
      - SEED_ADMIN_UID=${SEED_ADMIN_UID}
      - SEED_ADMIN_EMAIL=${SEED_ADMIN_EMAIL}
      - DEBUG=${DEBUG}
      - HUGGINGFACE_RISK_MODEL=${HUGGINGFACE_RISK_MODEL}
      - HUGGINGFACE_CATEGORY_MODEL=${HUGGINGFACE_CATEGORY_MODEL}
      - HF_HOME=/app/hf_cache
    volumes:
      - hf_cache:/app/hf_cache
      - uploads_data:/uploads
    deploy:
      resources:
        limits:
          cpus: '0.3'
          memory: 800M
    networks:
      - evd-network
  app.evd:
    image: ghcr.io/sistema-evaluacion-docente/app.evd:latest
    expose:
      - "80"
    environment:
      - VITE_API_URL=/api
      - VITE_FIREBASE_API_KEY=${VITE_FIREBASE_API_KEY}
      - VITE_FIREBASE_AUTH_DOMAIN=${VITE_FIREBASE_AUTH_DOMAIN}
      - VITE_FIREBASE_PROJECT_ID=${VITE_FIREBASE_PROJECT_ID}
      - VITE_FIREBASE_STORAGE_BUCKET=${VITE_FIREBASE_STORAGE_BUCKET}
      - VITE_FIREBASE_MESSAGING_SENDER_ID=${VITE_FIREBASE_MESSAGING_SENDER_ID}
      - VITE_FIREBASE_APP_ID=${VITE_FIREBASE_APP_ID}
      - VITE_NODE_ENV=production
    networks:
      - evd-network
    depends_on:
      - api.evd
      # - redis

volumes:
  hf_cache:
  uploads_data:
  # redis_data:

networks:
  evd-network:
